"""
GEMCO Excess Water Disposal L1 Summary Schedule Generator

This script converts the GEMCO L1 Summary Schedule Gantt chart data into a P6-compatible
Excel import template based on the 18030-PFS-CURRENT-1-Activities.xlsx structure.

Author: Generated by Claude Code
Date: 2026-01-21
"""

import openpyxl
from pathlib import Path

def generate_gemco_l1_schedule(template_path, output_path):
    """
    Generate GEMCO L1 Summary Schedule activities from visual Gantt chart data.

    Args:
        template_path: Path to the P6 import template Excel file
        output_path: Path where the output Excel file will be saved
    """

    # Load template
    wb = openpyxl.load_workbook(template_path)
    sheet = wb.active

    # Clear existing data rows (keep header)
    max_row = sheet.max_row
    if max_row > 1:
        sheet.delete_rows(2, max_row - 1)

    # GEMCO Excess Water Disposal L1 Summary Schedule Data
    # Format: (Activity ID, Status, WBS ID, Activity Name, Start Date, Finish Date, Duration in days)
    activities = [
        ('A1000', 'Not Started', 'GEMCO-L1.1', 'Submit SER to NT EPA', '', '', 30),
        ('A1010', 'Not Started', 'GEMCO-L1.2', 'Tier 2 Assessment by SER', '', '', 180),
        ('A1020', 'Not Started', 'GEMCO-L1.3', 'Primary Approval (Tier 2 Environmental)', '', '', 30),
        ('A1030', 'Not Started', 'GEMCO-L1.4', 'Secondary Approvals (Access agreement, Sacred Sites, Environmental Mining License)', '', '', 240),
        ('A1040', 'Not Started', 'GEMCO-L1.5', 'Secondary Approvals (Tier 2 Environmental)', '', '', 60),
        ('A1050', 'Not Started', 'GEMCO-L1.6', 'Secondary Approvals (Access agreement, Sacred Sites, Environmental Mining License)', '', '', 210),
        ('A1060', 'Not Started', 'GEMCO-L1.7', 'Tollgate Approval for ES to NH2', '', '', 60),
        ('A1070', 'Not Started', 'GEMCO-L1.8', 'FS Engineering - ES to NH2', '', '', 120),
        ('A1080', 'Not Started', 'GEMCO-L1.9', 'FS Engineering - NH2 to Ocean', '', '', 150),
        ('A1090', 'Not Started', 'GEMCO-L1.10', 'Tollgate Documentation, Review and Project Assurance', '', '', 60),
        ('A1100', 'Not Started', 'GEMCO-L1.11', 'Tollgate Approval for NH2 to Ocean', '', '', 60),
        ('A1110', 'Not Started', 'GEMCO-L1.12', 'FS to Exe Tollgate Approval (Dependent on Primary Approval)', '', '', 30),
        ('A1120', 'Not Started', 'GEMCO-L1.13', 'Preparation works for Tollgating - Partial Funding', '', '', 180),
        ('A1130', 'Not Started', 'GEMCO-L1.14', 'Tollgate Approval - Partial Funding', '', '', 60),
        ('A1140', 'Not Started', 'GEMCO-L1.15', 'Procurement of Pumps, HDPE Piping, Fuel Storage, Structural Fab, Gensets and custom pipe fittings', '', '', 90),
        ('A1150', 'Not Started', 'GEMCO-L1.16', 'Onshore Contractor MOB/Procurement', '', '', 90),
        ('A1160', 'Not Started', 'GEMCO-L1.17', 'Onshore Pipeline Installation', '', '', 180),
        ('A1170', 'Not Started', 'GEMCO-L1.18', 'Mining Preparation Activities', '', '', 120),
        ('A1180', 'Not Started', 'GEMCO-L1.19', 'SP1 Onshore Early Works', '', '', 60),
        ('A1190', 'Not Started', 'GEMCO-L1.20', 'SP2 - Onshore Pump Station Installation (SMP & E&I)', '', '', 90),
        ('A1200', 'Not Started', 'GEMCO-L1.21', 'S19 earthworks', '', '', 60),
        ('A1210', 'Not Started', 'GEMCO-L1.22', 'S19 Early Works', '', '', 60),
        ('A1220', 'Not Started', 'GEMCO-L1.23', 'Owners team preparation and onboarding', '', '', 90),
        ('A1230', 'Not Started', 'GEMCO-L1.24', 'Pre-commitment Approvals - Long Lead Items', '', '', 90),
        ('A1240', 'Not Started', 'GEMCO-L1.25', 'Procurement of HDPE Pipe & Fittings, Concrete Collars, Temp Sheet and Tube Piling, Concrete Mattresses, Steel Pipe & Vent Steel, Switchroom, Valves, Flow meters', '', '', 240),
        ('A1250', 'Not Started', 'GEMCO-L1.26', 'Offshore MOB', '', '', 60),
        ('A1260', 'Not Started', 'GEMCO-L1.27', 'King Pile Wall, Construct Truss Tower and Piping Installation', '', '', 90),
        ('A1270', 'Not Started', 'GEMCO-L1.28', 'Excavation & Backfill', '', '', 60),
        ('A1280', 'Not Started', 'GEMCO-L1.29', 'Commissioning', '', '', 60),
        ('A1290', 'Not Started', 'GEMCO-L1.30', 'Tie in pipeline onshore to offshore', '', '', 120),
        ('A1300', 'Not Started', 'GEMCO-L1.31', 'S19 Rehab', '', '', 60),
        ('A1310', 'Not Started', 'GEMCO-L1.32', 'Project Close Out', '', '', 60),
    ]

    # Populate sheet
    row_idx = 2
    for activity in activities:
        sheet.cell(row=row_idx, column=1, value=activity[0])  # task_code (A)
        sheet.cell(row=row_idx, column=2, value=activity[1])  # status_code (B)
        sheet.cell(row=row_idx, column=3, value=activity[2])  # wbs_id (C)
        sheet.cell(row=row_idx, column=4, value=activity[3])  # task_name (D)
        sheet.cell(row=row_idx, column=5, value=activity[4])  # start_date (E) - blank
        sheet.cell(row=row_idx, column=6, value=activity[5])  # end_date (F) - blank
        sheet.cell(row=row_idx, column=7, value=activity[6])  # target_drtn_hr_cnt (G) - duration in days
        sheet.cell(row=row_idx, column=8, value='')           # delete_record_flag (H)
        row_idx += 1

    # Save to output file
    wb.save(output_path)

    print(f'Successfully created {output_path} with {len(activities)} activities')
    print('\nFirst 5 activities:')
    for i, act in enumerate(activities[:5], 1):
        print(f'  {i}. {act[0]} - {act[3]} (Duration: {act[6]} days)')

    return len(activities)


if __name__ == '__main__':
    # Define paths
    project_root = Path(__file__).parent.parent.parent
    template_path = project_root / '18030-PFS-CURRENT-1-Activities.xlsx'
    output_path = project_root / 'summary_schedule_generator' / 'output' / 'excel' / 'GEMCO-L1-Summary-Schedule-Activities.xlsx'

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Generate schedule
    total_activities = generate_gemco_l1_schedule(str(template_path), str(output_path))

    print(f'\nGEMCO L1 Summary Schedule generated successfully')
    print(f'  Total activities: {total_activities}')
    print(f'  Output file: {output_path}')
